### ISSUE TITLE
Removable fields are not working with existing form data

### ISSUE THREAD

**Issue by kaphert** [validformbuilder/validformbuilder#94] opened 2017-07-17 15:36 UTC
### Actual behavior
If you create 3 dynamic areas and enter some values into the fields and press 'Submit'. You will see 3 times the dynamic area with the correct values. If you now remove one area from the list and press 'Submit' again the `valuesAsHtml()` output seems correct but the form still shows the (empty) dynamic area that was removed. 

The same problem occurs if you set defaults to the dynamic fields, see the commented lines). 
Currently I add `dynamic => true` to the fields of a dynamic area. This is not how it is supposed to work I suppose but it is the only way to use `setDefaults()` with dynamic areas. Otherwise it won't set the default form values and it throws a PHP warning. See issue #58 

The hidden dynamic counter is not updated at the moment you click on delete.

### Steps to reproduce the behavior and a code example

```php
$form = new ValidForm("form");
$area = $form->addArea("Dynamic Area",false, "dynamic-area", false, [
        "dynamic" => true,
        "dynamicLabel" => "+ add",
        "dynamicRemoveLabel" => "&times; delete"
    ]
);

$area->addField(
    "field-a",
    "field A",
    ValidForm::VFORM_STRING,
    [
    ],
    [
    ],
    [
        //"dynamic" => true,
    ]
);

$area->addField(
    "field-b",
    "field B",
    ValidForm::VFORM_STRING,
    [
    ],
    [
    ],
    [
        //"dynamic" => true,
    ]
);

// $form->setDefaults([ 'field-a' => [1,3,5],'field-b' => [2,4,6]]);

if ($form->isSubmitted() && $form->isValid()) {
    echo $form->valuesAsHtml();
}
echo $form->toHtml();

```

### Which version/branch of ValidForm Builder do you use?

I use version/branch: PR #25

**Comment by rvanbaalen** [comment] 2017-07-24 19:30
@kaphert 

> If you now remove one area from the list and press 'Submit' again the valuesAsHtml() output seems correct but the form still shows the (empty) dynamic area that was removed.

All ValidForm Builder examples point towards displaying the form OR displaying the form values after it's submitted. Like so:

```
if ($form->isSubmitted() && $form->isValid()) {
    echo $form->valuesAsHtml();
} else {
    echo $form->toHtml();
}
``` 

When I use that, I can't reproduce the first issue you mentioned, which I quoted above.

**Comment by rvanbaalen** [comment] 2017-07-25 19:47
Related: #95

**Comment by rvanbaalen** [comment] 2017-07-26 21:49
@kaphert Please test again this should be fixed in the latest version of this branch

**Comment by kaphert** [comment] 2017-07-27 12:14
Yes this ticket is resolved.

**Closed** 2017-12-14 10:18 UTC
Labels: php, priority: urgent, type: bug
